name: Scheduled build

on:
  schedule:
    # 月曜日の 11:00 (JST) に処理を実行する。
    # UTC の 02:00 は JST だと 11:00 。
    - cron: "*/10 * * * *"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python # Pythonのセットアップ
        uses: actions/setup-python@v2
        with:
          python-version: "3.9" # Pythonのバージョン指定
      - name: Install dependencies # 依存パッケージのインストール
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run right.py # PythonでRigthStufからデータ取得
        run: |
          python right.py
      - name: Commit and Push # 実行結果をプッシュしてレポジトリに反映
        run: |
          git config --local user.email "nasawake.am@gmail.com"
          git config --local user.name "tkgstrator"
          git add .
          git commit - m "Update product information" -a
          git pull
          git push origin master
