name: Scheduled build

on:
  push:
    branches:
      - develop
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node v16.15.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0

      - name: Cache CDK Dependencies
        uses: actions/cache@v3
        id: cache_cdk_dependency_id
        env:
          cache-name: cache-cdk-dependency
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install Dependencies
        if: ${{ steps.cache_cdk_dependency_id.outputs.cache-hit != 'true' }}
        run: yarn install

      - name: Format
        run: yarn format
      
      - name: Lint
        run: yarn lint

      - name: Retrieve Product Information
        run: yarn generate 
      
      - name: Build
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
